### PR TITLE
Refactor the SearchService a bit…

### PR DESCRIPTION
**Pull request by svanharmelen**
I started a review, but realised it would be faster to just write a PR with my take on it. So consider this my review :wink:

### CODE REVIEW

**Comment by Lorac** [comment]
@svanharmelen LGTM!. I need to remember that I can use private structures with a lowercase starting letter. Not used to it when you are doing C++ all day long.

I guess that's a bit of a older PR, so I didn't use the `ce` documentation link in that one. You might wanna fix that.

**Comment by svanharmelen** [comment]
@Lorac done... Through you've could have done that yourself as well of course :wink:

**Comment by Lorac** [comment]
@svanharmelen I could've :), but I was at work.

**Comment by svanharmelen** [comment]
Check... No problem 👍

**Pull request merged**
